# docker-compose.yml
version: '3.8'

services:
  dbt_duckdb:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dbt_duckdb
    volumes:
      - .:/app
      - C:\Users\Leonardo Villegas\.kaggle:/root/.kaggle:ro
    stdin_open: true
    tty: true